buildscript {
    ext.kotlin_version = "2.1.0"
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven {
            url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
        }
        maven {
            name = "IA SDK repo"
            url = uri("https://maven.pkg.github.com/ihreapotheken/IA-SDK-Android")
            credentials {
                username = System.getenv("GITHUB_USERNAME") ?: "mljubas@4ofthem.eu"
                password = System.getenv("GITHUB_TOKEN") ?: "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"
            }
        }
    }

    dependencies {
        classpath("com.android.tools.build:gradle:8.12.3")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version")
    }
}

allprojects {
  repositories {
      google()
      mavenCentral()
      gradlePluginPortal()
      maven {
          url = uri("https://api.mapbox.com/downloads/v2/releases/maven")
      }
      maven {
          name = "IA SDK repo"
          url = uri("https://maven.pkg.github.com/ihreapotheken/IA-SDK-Android")
          credentials {
              username = System.getenv("GITHUB_USERNAME") ?: "mljubas@4ofthem.eu"
              password = System.getenv("GITHUB_TOKEN") ?: "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"
          }
      }
  }
}

dependencies {
    def iaDeSdkVersion = "0.0.17-250"
    def iaDeSdkEnv = System.getenv("IA_DE_SDK_ENV") ?: "staging"
    def iaDeSdkDeps = [
            "de.ihreapotheken.sdk:integrations",
            "de.ihreapotheken.sdk:otc",
            "de.ihreapotheken.sdk:ordering",
            "de.ihreapotheken.sdk:pharmacy",
            "de.ihreapotheken.sdk:rx",
            "de.ihreapotheken.sdk:apofinder"
    ]
    iaDeSdkDeps.each { dep ->
        def fullDep = "${dep}${!iaDeSdkEnv.isBlank() ? "-${iaDeSdkEnv}" : ""}:${iaDeSdkVersion}"
        implementation fullDep
    }
    implementation("androidx.compose.material3:material3:1.3.1")
    def compose_version = "1.2.1"
    implementation "androidx.compose.ui:ui:$compose_version"
    // Tooling support (Previews, etc.)
    implementation "androidx.compose.ui:ui-tooling:$compose_version"
}

android {
    compileSdkVersion 36
    buildToolsVersion "36"

    defaultConfig {
        minSdkVersion 30
        targetSdkVersion 36

        versionCode 1
        versionName "1.0.0"

        generatedDensities = []
    }

    aaptOptions {
        additionalParameters "--no-version-vectors"
    }

    buildFeatures {
        compose true
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }

    composeOptions {
        kotlinCompilerExtensionVersion '1.3.2'
    }
}
