name: Package Deploy

# This workflow runs when any of the following occur:
# - A push is made to a branch called `main` or `develop`
# - A tag starting with "v" is created
# - A pull request is created or updated
on:
  push:
    branches:
      - main
      - develop
    tags:
      - v*
  pull_request:
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ihreapotheken'
      - name: Publish package
        run: cd packages/ia-sdk && pwd && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}